parameters:
    ventasbundle.venta:
    
    ventasbundle.ticket:

    ventasbundle.generador:
        seccion: 'Venta'
        subseccion: 'Generar nueva venta'
        nombrelogicobundle: 'RGMELibreriaVentasBundle'
        path: 'GeneradorVenta'
        plantillas:
            editor: 'editorVenta.html.twig'
            menu_izq: 'RGMELibreriaIndexBundle::menu_izq_vacio.html.twig'
            plantillaItem: 'plantillaItem.html.twig'
            
        entidad:
            repositorio: 'Venta'
            clase: 'RGM\eLibreria\VentasBundle\Entity\Venta'
            
        itemVenta:
            clase: 'RGM\eLibreria\VentasBundle\Entity\ItemVenta'
            
        cliente:
            repositorio: 'Cliente'
            clase: 'RGM\eLibreria\VentasBundle\Entity\Cliente'
            
        localizacion:
            repositorio: 'RGMELibreriaLibroBundle:Localizacion'
            
        existencias:
            articulo:
                repositorio: 'RGMeLibreriaExistenciaBundle:ExistenciaArticulo'
                
            libro:
                repositorio: 'RGMeLibreriaExistenciaBundle:ExistenciaLibro'
                        
        ajax:
            ruta_cliente_get_info: 'rgm_e_libreria_venta_get_info_cliente'
            ruta_cliente_set_nuevo: 'rgm_e_libreria_venta_crear_nuevo_cliente'
            ruta_ajax_buscar_ref: 'rgm_e_libreria_venta_buscar_ref'
            ruta_ajax_buscar_titulo: 'rgm_e_libreria_venta_buscar_titulo'
            ruta_ajax_plantilla_existencia: 'rgm_e_libreria_venta_plantilla_existencia'
            ruta_ajax_registro_venta: 'rgm_e_libreria_venta_registro_venta'