parameters:
    ventasbundle.venta:
        inicio: 'rgm_e_libreria_ventas_index'
        seccion: 'Gestión de Ventas'
        subseccion: 'Registro de Ventas'
        nombrelogicobundle: 'RGMELibreriaVentasBundle'
        path: 'Venta'
        formularios:
            visor: 'RGM\eLibreria\VentasBundle\Form\Frontend\Venta\VentaVisorType'
            
        entidad: 
            repositorio: 'Venta'
            clase: 'RGM\eLibreria\VentasBundle\Entity\Venta'
            
        plantillas:
            principal: 'RGMELibreriaIndexBundle:Grid:verEntidad.html.twig'
            gestorVenta: 'gestorVenta.html.twig'
            vm_formularios: 'RGMELibreriaIndexBundle:VentanaModal:vm_formularios_estandar.html.twig'
        
        ruta_form_crear: 'rgm_e_libreria_ventas_crear'
        titulo_crear: 'Crear nueva venta'
        titulo_submit_crear: 'Crear'
        flash_crear: 'Venta creada con éxito'
        
        grid_ruta_editar: 'rgm_e_libreria_ventas_editar'
        titulo_editar: 'Editar venta'
        grid_boton_editar: 'Editar'
        flash_editar: 'Venta editada con éxito'
        
        ruta_ticket: 'rgm_e_libreria_ventas_ticket_ver'
        
        grid_ruta_borrar: 'rgm_e_libreria_ventas_borrar'
        titulo_borrar: 'Confirmar Borrado'
        msg_borrar: 'Se va a proceder a borrar los siguientes datos. (Esta acción liberará todas aquellas existencias vendidas)'
        titulo_form_borrar: 'Borrar venta'
        msg_confirmar_borrar: '¿Realmente desea realizar la accion?'
        grid_boton_borrar: 'Borrar'
        titulo_submit_borrar: '¡Si, Estoy seguro!'
        flash_borrar: 'Venta borrada con éxito'
        
    ventasbundle.cliente:
        inicio: 'rgm_e_libreria_cliente_index'
        seccion: 'Gestión de Ventas'
        subseccion: 'Registro de Clientes'
        nombrelogicobundle: 'RGMELibreriaVentasBundle'
        path: 'Cliente'
        formularios:
            editor: 'RGM\eLibreria\VentasBundle\Form\Frontend\Cliente\ClienteType'
            visor: 'RGM\eLibreria\VentasBundle\Form\Frontend\Cliente\ClienteVisorType'
            
        entidad: 
            repositorio: 'Cliente'
            clase: 'RGM\eLibreria\VentasBundle\Entity\Cliente'
            
        plantillas:
            principal: 'RGMELibreriaIndexBundle:Grid:verEntidad.html.twig'
            vm_formularios: 'RGMELibreriaIndexBundle:VentanaModal:vm_formularios_estandar.html.twig'
        
        ruta_form_crear: 'rgm_e_libreria_cliente_crear'
        titulo_crear: 'Crear nuevo cliente'
        titulo_submit_crear: 'Crear'
        flash_crear: 'Cliente creado con éxito'
        
        grid_ruta_editar: 'rgm_e_libreria_cliente_editar'
        titulo_editar: 'Editar cliente'
        grid_boton_editar: 'Editar'
        flash_editar: 'Cliente editado con éxito'
        
        grid_ruta_borrar: 'rgm_e_libreria_cliente_borrar'
        titulo_borrar: 'Confirmar Borrado'
        msg_borrar: 'Se va a proceder a borrar los siguientes datos.'
        titulo_form_borrar: 'Borrar cliente'
        msg_confirmar_borrar: '¿Realmente desea realizar la acción?'
        grid_boton_borrar: 'Borrar'
        titulo_submit_borrar: '¡Si, Estoy seguro!'
        flash_borrar: 'Cliente borrado con éxito'
    
    ventasbundle.ticket:
        venta:
            repositorio: 'RGMELibreriaVentasBundle:Venta'
            
    ventasbundle.informeventa:
        inicio: 'rgm_e_libreria_ventas_informe_index'
        seccion: 'Gestión de Ventas'
        subseccion: 'Informe de Ventas'
        nombrelogicobundle: 'RGMELibreriaVentasBundle'
        path: 'InformeVenta'
        venta:
            repositorio: 'RGMELibreriaVentasBundle:Venta'
        plantillas:
            principal: 'informe.html.twig'
            principal2: 'informe2.html.twig'
        formularios:
            seleccionInforme: 'RGM\eLibreria\VentasBundle\Form\Frontend\InformeVenta\InformeType'
        

    ventasbundle.generador:
        inicio: 'rgm_e_libreria_ventas_index'
        seccion: 'Venta'
        subseccion: 'Editor de venta'
        nombrelogicobundle: 'RGMELibreriaVentasBundle'
        path: 'GeneradorVenta'
        plantillas:
            editor: 'editorVenta.html.twig'
            menu_izq: 'RGMELibreriaIndexBundle::menu_izq_vacio.html.twig'
            plantillaItem: 'plantillaItem.html.twig'
            
        entidad:
            repositorio: 'Venta'
            clase: 'RGM\eLibreria\VentasBundle\Entity\Venta'
            
        itemVenta:
            clase: 'RGM\eLibreria\VentasBundle\Entity\ItemVenta'
            
        cliente:
            repositorio: 'Cliente'
            clase: 'RGM\eLibreria\VentasBundle\Entity\Cliente'
            
        localizacion:
            repositorio: 'RGMELibreriaLibroBundle:Localizacion'
            
        existencias:
            articulo:
                repositorio: 'RGMeLibreriaExistenciaBundle:ExistenciaArticulo'
                
            libro:
                repositorio: 'RGMeLibreriaExistenciaBundle:ExistenciaLibro'
                
        ruta_ticket: 'rgm_e_libreria_ventas_ticket_ver'
                        
        ajax:
            ruta_cliente_get_info: 'rgm_e_libreria_venta_get_info_cliente'
            ruta_cliente_set_nuevo: 'rgm_e_libreria_venta_crear_nuevo_cliente'
            ruta_ajax_buscar_ref: 'rgm_e_libreria_venta_buscar_ref'
            ruta_ajax_buscar_titulo: 'rgm_e_libreria_venta_buscar_titulo'
            ruta_ajax_plantilla_existencia: 'rgm_e_libreria_venta_plantilla_existencia'
            ruta_ajax_registro_venta: 'rgm_e_libreria_venta_registro_venta'
            ruta_ajax_borrar_existencia: 'rgm_e_libreria_venta_borrar_existencia'
            ruta_ajax_get_ruta_ticket: 'rgm_e_libreria_venta_get_ruta_ticket'