rgm_e_libreria_ventas_ticket_ver:
    pattern: /ticket/ver
    defaults: { _controller: 'RGMELibreriaVentasBundle:Ticket:verTicket' }
    
    
    
rgm_e_libreria_ventas_crear:
    pattern: /venta/nueva
    defaults: { _controller: 'RGMELibreriaVentasBundle:GeneradorVenta:generadorVenta' }
    
rgm_e_libreria_venta_plantilla_existencia:
    pattern: /venta/ajax/plantilla/existencia
    defaults: { _controller: 'RGMELibreriaVentasBundle:GeneradorVenta:plantillaExistencia' }
    methods:  [POST]    
    
    

rgm_e_libreria_venta_get_info_cliente:
    pattern: /venta/ajax/cliente/info
    defaults: { _controller: 'RGMELibreriaVentasBundle:GeneradorVenta:getInfoCliente' }
    methods:  [POST]
    
rgm_e_libreria_venta_crear_nuevo_cliente:
    pattern: /venta/ajax/cliente/nuevo
    defaults: { _controller: 'RGMELibreriaVentasBundle:GeneradorVenta:setNuevoCliente' }
    methods:  [POST]
    
rgm_e_libreria_venta_buscar_ref:
    pattern: /venta/ajax/buscar/ref
    defaults: { _controller: 'RGMELibreriaVentasBundle:GeneradorVenta:buscarRef' }
    methods:  [POST]
    
rgm_e_libreria_venta_buscar_titulo:
    pattern: /venta/ajax/buscar/titulo
    defaults: { _controller: 'RGMELibreriaVentasBundle:GeneradorVenta:buscarTitulo' }
    methods:  [POST]
    
    
    
rgm_e_libreria_ventas_editar:
    pattern: /gestor/editar/{id}
    defaults: { _controller: 'RGMELibreriaVentasBundle:Venta:editarVenta' }
    
rgm_e_libreria_ventas_borrar:
    pattern: /gestor/borrar/{id}
    defaults: { _controller: 'RGMELibreriaVentasBundle:Venta:borrarVenta' }
    
rgm_e_libreria_ventas_index:
    pattern: /gestor
    defaults: { _controller: 'RGMELibreriaVentasBundle:Venta:verVentas' }