rgm_e_libreria_ventas_ticket_ver:
    pattern: /ticket/ver
    defaults: { _controller: 'RGMELibreriaVentasBundle:Ticket:verTicket' }
    
    
    
rgm_e_libreria_ventas_crear:
    pattern: /venta/nueva
    defaults: { _controller: 'RGMELibreriaVentasBundle:Venta:crearVenta' }
    
    
    
rgm_e_libreria_ventas_editar:
    pattern: /gestor/editar/{id}
    defaults: { _controller: 'RGMELibreriaVentasBundle:Venta:editarVenta' }
    
rgm_e_libreria_ventas_borrar:
    pattern: /gestor/borrar/{id}
    defaults: { _controller: 'RGMELibreriaVentasBundle:Venta:borrarVenta' }
    
rgm_e_libreria_ventas_index:
    pattern: /gestor
    defaults: { _controller: 'RGMELibreriaVentasBundle:Venta:verVentas' }