rgme_libreria_existencia:
    resource: "@RGMeLibreriaExistenciaBundle/Resources/config/routing.yml"
    prefix:   /existencias

rgme_libreria_reservas:
    resource: "@RGMeLibreriaReservasBundle/Resources/config/routing.yml"
    prefix:   /reservas
    
rgme_libreria_ventas:
    resource: "@RGMELibreriaVentasBundle/Resources/config/routing.yml"
    prefix:   /ventas

rgme_libreria_suministro:
    resource: "@RGMELibreriaSuministroBundle/Resources/config/routing.yml"
    prefix:   /suministro

rgme_libreria_financiacion:
    resource: "@RGMELibreriaFinanciacionBundle/Resources/config/routing.yml"
    prefix:   /financiacion

rgme_libreria_libro:
    resource: "@RGMELibreriaLibroBundle/Resources/config/routing.yml"
    prefix:   /libro

rgme_libreria_empresa:
    resource: "@RGMELibreriaEmpresaBundle/Resources/config/routing.yml"
    prefix:   /empresa

rgme_libreria_usuario:
    resource: "@RGMELibreriaUsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario

rgme_libreria_index:
    resource: "@RGMELibreriaIndexBundle/Resources/config/routing.yml"
    prefix:   /
