security:
    role_hierarchy:
        ROLE_ADMIN:   ROLE_USUARIO
        ROLE_SADMIN: [ROLE_USUARIO, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    encoders:
        RGM\eLibreria\UsuarioBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }
        Symfony\Component\Security\Core\User\User: { algorithm: sha512, iterations: 10 }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        frontend:
            pattern:     ^/
            anonymous:   ~
            form_login:
                login_path: /usuario/login
                check_path: /usuario/login_check
            logout:
                path:   /usuario/logout
                target: /

    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/*, roles: ROLE_ADMIN }
        - { path: ^/*, roles: ROLE_USUARIO }

    providers:
        todos:
            chain:
                providers: [in_memory, usuarios]
            
        in_memory:
            memory:
                users:
                    super_admin: { password: sa, roles: [ 'ROLE_SADMIN' ] }
        
        usuarios:
            entity: { class: RGM\eLibreria\UsuarioBundle\Entity\Usuario, property: username }