parameters:
    suministrobundle.distribuidora:
        inicio: 'rgm_e_libreria_suministro_distribuidoras_homepage'
        seccion: 'Gestión de suministros'
        subseccion: 'Distribuidoras'
        nombrelogicobundle: 'RGMELibreriaSuministroBundle'
        path: 'Distribuidoras'
        formularios:
            editor: 'RGM\eLibreria\SuministroBundle\Form\Frontend\Distribuidora\DistribuidoraType'
            visor: 'RGM\eLibreria\SuministroBundle\Form\Frontend\Distribuidora\DistribuidoraVisorType'
        entidad: 'Distribuidora'
        clase_entidad: 'RGM\eLibreria\SuministroBundle\Entity\Distribuidora'
        plantillas:
            principal: 'RGMELibreriaIndexBundle:Grid:verEntidad.html.twig'
            vm_formularios: 'RGMELibreriaIndexBundle:VentanaModal:vm_formularios_estandar.html.twig'
        
        ruta_form_crear: 'rgm_e_libreria_suministro_distribuidoras_crear'
        titulo_crear: 'Crear nueva distribuidora'
        titulo_submit_crear: 'Crear'
        flash_crear: 'Distribuidora creada con éxito'
        
        grid_ruta_editar: 'rgm_e_libreria_suministro_distribuidoras_editar'
        titulo_editar: 'Editar distribuidora'
        grid_boton_editar: 'Editar'
        flash_editar: 'Distribuidora editada con éxito'
        
        grid_ruta_borrar: 'rgm_e_libreria_suministro_distribuidoras_borrar'
        titulo_borrar: 'Confirmar Borrado'
        msg_borrar: 'Se va a proceder a borrar los siguientes datos.'
        titulo_form_borrar: 'Borrar distribuidora'
        msg_confirmar_borrar: '¿Realmente desea realizar la acción?'
        grid_boton_borrar: 'Borrar'
        titulo_submit_borrar: '¡Si, Estoy seguro!'
        flash_borrar: 'Distribuidora borrada con éxito'
        
    suministrobundle.recargo:
        inicio: 'rgm_e_libreria_suministro_recargo_homepage'
        seccion: 'Gestión de suministros'
        subseccion: 'Recargos de equivalencia'
        nombrelogicobundle: 'RGMELibreriaSuministroBundle'
        path: 'Recargo'
        formularios:
            editor: 'RGM\eLibreria\SuministroBundle\Form\Frontend\Recargo\RecargoType'
            visor: 'RGM\eLibreria\SuministroBundle\Form\Frontend\Recargo\RecargoVisorType'
        entidad: 'Recargo'
        clase_entidad: 'RGM\eLibreria\SuministroBundle\Entity\Recargo'
        plantillas:
            principal: 'RGMELibreriaIndexBundle:Grid:verEntidad.html.twig'
            vm_formularios: 'RGMELibreriaIndexBundle:VentanaModal:vm_formularios_estandar.html.twig'
        
        ruta_form_crear: 'rgm_e_libreria_suministro_recargo_crear'
        titulo_crear: 'Crear nuevo recargo'
        titulo_submit_crear: 'Crear'
        flash_crear: 'Recargo creado con éxito'
        
        grid_ruta_editar: 'rgm_e_libreria_suministro_recargo_editar'
        titulo_editar: 'Editar recargo'
        grid_boton_editar: 'Editar'
        flash_editar: 'Recargo editado con éxito'
        
        grid_ruta_borrar: 'rgm_e_libreria_suministro_recargo_borrar'
        titulo_borrar: 'Confirmar Borrado'
        msg_borrar: 'Se va a proceder a borrar los siguientes datos.'
        titulo_form_borrar: 'Borrar recargo'
        msg_confirmar_borrar: '¿Realmente desea realizar la acción?'
        grid_boton_borrar: 'Borrar'
        titulo_submit_borrar: '¡Si, Estoy seguro!'
        flash_borrar: 'Recargo borrado con éxito'
        
    suministrobundle.contrato:
        inicio: 'rgm_e_libreria_suministro_contratosuministro_homepage'
        seccion: 'Gestión de suministros'
        subseccion: 'Contratos de suministro'
        nombrelogicobundle: 'RGMELibreriaSuministroBundle'
        path: 'ContratoSuministro'
        formularios:
            editor: 'RGM\eLibreria\SuministroBundle\Form\Frontend\ContratoSuministro\ContratoSuministroType'
            visor: 'RGM\eLibreria\SuministroBundle\Form\Frontend\ContratoSuministro\ContratoSuministroVisorType'
        entidad: 'ContratoSuministro'
        clase_entidad: 'RGM\eLibreria\SuministroBundle\Entity\ContratoSuministro'
        plantillas:
            principal: 'RGMELibreriaIndexBundle:Grid:verEntidad.html.twig'
            vm_formularios: 'RGMELibreriaIndexBundle:VentanaModal:vm_formularios_estandar.html.twig'
        
        ruta_form_crear: 'rgm_e_libreria_suministro_contratosuministro_crear'
        titulo_crear: 'Crear nuevo contrato'
        titulo_submit_crear: 'Crear'
        flash_crear: 'Contrato de suministro creado con éxito'
        
        grid_ruta_editar: 'rgm_e_libreria_suministro_contratosuministro_editar'
        titulo_editar: 'Editar contrato'
        grid_boton_editar: 'Editar'
        flash_editar: 'Contrato de suministro editado con éxito'
        
        grid_ruta_borrar: 'rgm_e_libreria_suministro_contratosuministro_borrar'
        titulo_borrar: 'Confirmar Borrado'
        msg_borrar: 'Se va a proceder a borrar los siguientes datos.'
        titulo_form_borrar: 'Borrar contrato'
        msg_confirmar_borrar: '¿Realmente desea realizar la acción?'
        grid_boton_borrar: 'Borrar'
        titulo_submit_borrar: '¡Si, Estoy seguro!'
        flash_borrar: 'Contrato de suministro borrado con éxito'
        
    suministrobundle.albaran:
        inicio: 'rgm_e_libreria_suministro_albaran_homepage'
        seccion: 'Gestión de suministros'
        subseccion: 'Albaranes'
        nombrelogicobundle: 'RGMELibreriaSuministroBundle'
        path: 'Albaran'
        formularios:
            editor: 'RGM\eLibreria\SuministroBundle\Form\Frontend\Albaran\AlbaranType'
            visor: 'RGM\eLibreria\SuministroBundle\Form\Frontend\Albaran\AlbaranVisorType'
        entidad: 'Albaran'
        clase_entidad: 'RGM\eLibreria\SuministroBundle\Entity\Albaran'
        plantillas:
            principal: 'RGMELibreriaIndexBundle:Grid:verEntidad.html.twig'
            crearAlbaran: 'crearAlbaran.html.twig'
            vm_formularios: 'RGMELibreriaIndexBundle:VentanaModal:vm_formularios_estandar.html.twig'
            plantillaLibro: 'plantillaLibro.html.twig'
            plantillaExistencia: 'plantillaExistencia.html.twig'
            plantillaCrearMasivoExistencia: 'plantillaCrearMasivoExistencia.html.twig'
            plantillaArticulo: 'plantillaArticulo.html.twig'
            ver: 'verAlbaran.html.twig'
            verAB: 'verAbono.html.twig'
            
        impresion:
            numElementosPagina: 33
            
        contrato:
            repositorio: 'RGMELibreriaSuministroBundle:ContratoSuministro'
            
        libro:
            repositorio: 'RGMELibreriaLibroBundle:Libro'
            entidad: 'RGM\eLibreria\LibroBundle\Entity\Libro'
            
        articulo:
            repositorio: 'RGMELibreriaSuministroBundle:Articulo'
            entidad: 'RGM\eLibreria\SuministroBundle\Entity\Articulo'
            
        ejemplar:
            repositorio: 'RGMELibreriaLibroBundle:Ejemplar'
            entidad: 'RGM\eLibreria\LibroBundle\Entity\Ejemplar'
            
        existencias:
            libro:
                repositorio: 'RGMeLibreriaExistenciaBundle:ExistenciaLibro'
                clase: 'RGM\eLibreria\ExistenciaBundle\Entity\ExistenciaLibro'
            
            articulo:
                repositorio: 'RGMeLibreriaExistenciaBundle:ExistenciaArticulo'
                clase: 'RGM\eLibreria\ExistenciaBundle\Entity\ExistenciaArticulo'
            
        itemAlbaran:
            entidad: 'RGM\eLibreria\SuministroBundle\Entity\ItemAlbaran'
            
        localizacion:
            repositorio: 'RGMELibreriaLibroBundle:Localizacion'
            entidad: 'RGM\eLibreria\LibroBundle\Entity\Localizacion'
            
        recargo:
            repositorio: 'RGMELibreriaSuministroBundle:Recargo'
            
        editorial:
            repositorio: 'RGMELibreriaLibroBundle:Editorial'
            entidad: 'RGM\eLibreria\LibroBundle\Entity\Editorial'
            
        autor:
            repositorio: 'RGMELibreriaLibroBundle:Autor'
            
        estilo:
            repositorio: 'RGMELibreriaLibroBundle:Estilo'
            
        ajax:
            ruta_ajax_registro_albaran: 'rgm_e_libreria_suministro_albaran_ajax_registro_albaran'
            ruta_ajax_get_items_albaran: 'rgm_e_libreria_suministro_albaran_ajax_get_items_albaran'
            
            ruta_ajax_get_datos_libro: 'rgm_e_libreria_suministro_albaran_ajax_get_datos_libro'
            ruta_ajax_get_datos_articulo: 'rgm_e_libreria_suministro_albaran_ajax_get_datos_articulo'
            ruta_ajax_get_datos_existencia: 'rgm_e_libreria_suministro_albaran_ajax_get_datos_existencia'
            
            ruta_ajax_buscar_libros: 'rgm_e_libreria_librobundle_libro_buscar_referencia_ajax'
            ruta_ajax_buscar_articulos: 'rgm_e_libreria_suministro_articulo_buscar_referencia_ajax'
            ruta_ajax_buscar_editoriales: 'rgarcia_entrelineas_editorial_buscarAjax'
            
            ruta_ajax_registro_libro: 'rgm_e_libreria_suministro_albaran_ajax_registro_libro'
            ruta_ajax_registro_articulo: 'rgm_e_libreria_suministro_albaran_ajax_registro_articulo'
            ruta_ajax_registro_existencia: 'rgm_e_libreria_suministro_albaran_ajax_registro_existencia'
            
            ruta_ajax_borrar_existencia: 'rgm_e_libreria_suministro_albaran_ajax_borrar_existencia'
            
            ruta_ajax_plantilla_libro: 'rgm_e_libreria_suministro_albaran_ajax_plantilla_libro'
            ruta_ajax_plantilla_articulo: 'rgm_e_libreria_suministro_albaran_ajax_plantilla_articulo'
            ruta_ajax_plantilla_existencia: 'rgm_e_libreria_suministro_albaran_ajax_plantilla_existencia'
                    
        ruta_form_crear: 'rgm_e_libreria_suministro_editor_albaran_crear'
        titulo_crear: 'Crear nuevo contrato'
        titulo_submit_crear: 'Crear'
        
        grid_ruta_editar: 'rgm_e_libreria_suministro_editor_albaran_editar'
        grid_boton_editar: 'Editar'
        
        grid_ruta_borrar: 'rgm_e_libreria_suministro_albaran_borrar'
        titulo_borrar: 'Confirmar Borrado'
        msg_borrar: 'Se va a proceder a borrar los siguientes datos.'
        titulo_form_borrar: 'Borrar albarán'
        msg_confirmar_borrar: '¿Realmente desea realizar la acción?'
        grid_boton_borrar: 'Borrar'
        titulo_submit_borrar: '¡Si, Estoy seguro!'
        flash_borrar: 'Albarán borrado con éxito'
        
    suministrobundle.articulo:
        inicio: 'rgm_e_libreria_suministro_articulo_homepage'
        seccion: 'Gestión de articulos'
        subseccion: 'Articulos'
        nombrelogicobundle: 'RGMELibreriaSuministroBundle'
        path: 'Articulo'
        tipoNoConformidad: 'Tipo de No Conformidad'
        formularios:
            editor: 'RGM\eLibreria\SuministroBundle\Form\Frontend\Articulo\ArticuloType'
            visor: 'RGM\eLibreria\SuministroBundle\Form\Frontend\Articulo\ArticuloVisorType'
            
        entidad: 
            repositorio: 'Articulo'
            clase: 'RGM\eLibreria\SuministroBundle\Entity\Articulo'
            
        plantillas:
            principal: 'RGMELibreriaIndexBundle:Grid:verEntidad.html.twig'
            vm_formularios: 'RGMELibreriaIndexBundle:VentanaModal:vm_formularios_estandar.html.twig'

        ruta_form_crear: 'rgm_e_libreria_suministro_articulo_crear'
        titulo_crear: 'Crear nuevo articulo'
        titulo_submit_crear: 'Crear'
        flash_crear: 'Articulo creada con éxito'
        
        grid_ruta_editar: 'rgm_e_libreria_suministro_articulo_editar'
        titulo_editar: 'Editar articulo'
        grid_boton_editar: 'Editar'
        flash_editar: 'Articulo editado con éxito'
        
        grid_ruta_borrar: 'rgm_e_libreria_suministro_articulo_borrar'
        titulo_borrar: 'Confirmar Borrado'
        msg_borrar: 'Se va a proceder a borrar los siguientes datos.'
        titulo_form_borrar: 'Borrar articulo'
        msg_confirmar_borrar: '¿Realmente desea realizar la acción?'
        grid_boton_borrar: 'Borrar'
        titulo_submit_borrar: '¡Si, Estoy seguro!'
        flash_borrar: 'Articulo borrado con éxito'