rgm_e_libreria_suministro_editor_albaran_crear:
    pattern: /albaran2/crear
    defaults: { _controller: 'RGMELibreriaSuministroBundle:EditorAlbaran:editarAlbaran' }
    
rgm_e_libreria_suministro_editor_albaran_editar:
    pattern: /albaran2/editar/{id}
    defaults: { _controller: 'RGMELibreriaSuministroBundle:EditorAlbaran:editarAlbaran' }
    
rgm_e_libreria_suministro_albaran_crear:
    pattern: /albaran2/crear
    defaults: { _controller: 'RGMELibreriaSuministroBundle:EditorAlbaran:editarAlbaran' }

rgm_e_libreria_suministro_albaran_importar:
    pattern: /albaran/importar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Albaran:importar' }

rgm_e_libreria_suministrobundle_albaran_buscar_referencia_ajax:
    pattern: /albaran/buscarAjax
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Albaran:buscarAjax' }

rgm_e_libreria_suministro_albaran_ver:
    pattern: /albaran/{id}/ver
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Albaran:verAlbaran' }
    
rgm_e_libreria_suministro_albaran_borrar:
    pattern: /albaran/{id}/borrar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Albaran:borrarAlbaran' }
    
rgm_e_libreria_suministro_albaran_homepage:
    pattern: /albaran
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Albaran:verAlbaranes' }
    


rgm_e_libreria_suministro_albaran_crear_ajax_registro_libros_albaran:
    pattern: /ajax/registro/libros
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:registroLibro' }
    methods:  [POST]

rgm_e_libreria_suministro_albaran_crear_ajax_registro_ejemplar:
    pattern: /ajax/registro/ejemplar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:registroEjemplar' }
    methods:  [POST]
    
rgm_e_libreria_suministro_albaran_crear_ajax_registro:
    pattern: /ajax/registro
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:registroAlbaran' }
    methods:  [POST]
    
rgm_e_libreria_suministro_albaran_crear_ajax_eliminar_libro:
    pattern: /ajax/eliminar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:eliminarLibro' }
    methods:  [POST]
    
rgm_e_libreria_suministro_albaran_crear_ajax_plantilla_datos_libro:
    pattern: /ajax/plantilla/libro
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:getPlantillaLibro' }
    
rgm_e_libreria_suministro_albaran_crear_ajax_plantilla_ejemplar:
    pattern: /ajax/plantilla/ejemplar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:getPlantillaEjemplar' }

rgm_e_libreria_suministro_albaran_crear_ajax_get_items_albaran:
    pattern: /ajax/items
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:getItemsAlbaran' }
    methods:  [POST]

rgm_e_libreria_suministro_albaran_crear_ajax_get_datos_libro:
    pattern: /ajax/datos-libro
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:getDatosLibro' }
    methods:  [POST]
    
rgm_e_libreria_suministro_albaran_crear_ajax_get_datos_ejemplar:
    pattern: /ajax/datos-ejemplar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:getDatosEjemplar' }
    methods:  [POST]
    
rgm_e_libreria_suministro_albaran_borrar_ejemplar:
    pattern: /ajax/borrar-ejemplar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:borrarEjemplar' }
    methods:  [POST]
    
rgm_e_libreria_suministro_albaran_ejemplares_libro_albaran:
    pattern: /ajax/ejemplares/libro/albaran
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:getEjemplaresLibroAlbaran' }
    methods:  [POST]



rgm_e_libreria_suministro_albaran_ajax_plantilla:
    pattern: /ajax/ejemplar/plantilla
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:getPlantillaEjemplar' }

rgm_e_libreria_suministro_albaran_ajax_nuevo_ejemplar:
    pattern: /ajax/ejemplar/nuevo/{idAlbaran}/{idLibro}
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:crearEjemplar' }

rgm_e_libreria_suministro_albaran_ajax_editar_ejemplar:
    pattern: /ajax/ejemplar/nuevo/{idAlbaran}/{idLibro}/{idEjemplar}
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:editarEjemplar' }

rgm_e_libreria_suministro_albaran_ajax_borrar_ejemplar:
    pattern: /ajax/ejemplar/nuevo/{idAlbaran}/{idLibro}/{idEjemplar}
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:borrarEjemplar' }
    

rgm_e_libreria_suministro_contratosuministro_crear:
    pattern:  /contratosuministro/nuevo
    defaults: { _controller: 'RGMELibreriaSuministroBundle:ContratoSuministro:crearContratoSuministro' }
    
rgm_e_libreria_suministro_contratosuministro_editar:
    pattern:  /contratosuministro/{id}/editar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:ContratoSuministro:editarContratoSuministro' }
    
rgm_e_libreria_suministro_contratosuministro_borrar:
    pattern:  /contratosuministro/{id}/borrar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:ContratoSuministro:borrarContratoSuministro' }
    
rgm_e_libreria_suministro_contratosuministro_homepage:
    pattern:  /contratosuministro
    defaults: { _controller: 'RGMELibreriaSuministroBundle:ContratoSuministro:verContratosSuministro' }
    
    
    

rgm_e_libreria_suministro_recargo_crear:
    pattern:  /recargo/nueva
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Recargo:crearRecargo' }
    
rgm_e_libreria_suministro_recargo_editar:
    pattern:  /recargo/{id}/editar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Recargo:editarRecargo' }
    
rgm_e_libreria_suministro_recargo_borrar:
    pattern:  /recargo/{id}/borrar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Recargo:borrarRecargo' }
    
rgm_e_libreria_suministro_recargo_homepage:
    pattern:  /recargo
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Recargo:verRecargos' }    
    
    

rgm_e_libreria_suministro_distribuidoras_crear:
    pattern:  /distribuidoras/nueva
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Distribuidora:crearDistribuidora' }
    
rgm_e_libreria_suministro_distribuidoras_editar:
    pattern:  /distribuidoras/{id}/editar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Distribuidora:editarDistribuidora' }
    
rgm_e_libreria_suministro_distribuidoras_borrar:
    pattern:  /distribuidoras/{id}/borrar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Distribuidora:borrarDistribuidora' }
    
rgm_e_libreria_suministro_distribuidoras_homepage:
    pattern:  /distribuidoras
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Distribuidora:verDistribuidoras' }