rgm_e_libreria_suministro_editor_albaran_crear:
    pattern: /albaran2/crear
    defaults: { _controller: 'RGMELibreriaSuministroBundle:EditorAlbaran:editarAlbaran' }
    
rgm_e_libreria_suministro_editor_albaran_editar:
    pattern: /albaran2/editar/{id}
    defaults: { _controller: 'RGMELibreriaSuministroBundle:EditorAlbaran:editarAlbaran' }
    
rgm_e_libreria_suministro_albaran_crear:
    pattern: /albaran2/crear
    defaults: { _controller: 'RGMELibreriaSuministroBundle:EditorAlbaran:editarAlbaran' }

rgm_e_libreria_suministro_albaran_importar:
    pattern: /albaran/importar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Albaran:importar' }

rgm_e_libreria_suministrobundle_albaran_buscar_referencia_ajax:
    pattern: /albaran/buscarAjax
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Albaran:buscarAjax' }

rgm_e_libreria_suministro_albaran_ver:
    pattern: /albaran/{id}/ver
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Albaran:verAlbaran' }

rgm_e_libreria_suministro_albaran_verAB:
    pattern: /albaran/{id}/verAB
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Albaran:verAbono' }
    
rgm_e_libreria_suministro_albaran_borrar:
    pattern: /albaran/{id}/borrar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Albaran:borrarAlbaran' }
    
rgm_e_libreria_suministro_albaran_liquidarTotal:
    pattern: /albaran/{id}/liquidacionTotal
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Albaran:liquidacionTotal' }
    
rgm_e_libreria_suministro_albaran_homepage:
    pattern: /albaran
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Albaran:verAlbaranes' }
    
    
    
    
            

rgm_e_libreria_suministro_albaran_ajax_registro_albaran:
    pattern: /ajax/registro/albaran
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:registroAlbaran' }
    methods:  [POST]

rgm_e_libreria_suministro_albaran_ajax_get_items_albaran:
    pattern: /ajax/peticion/items
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:peticionItems' }
    methods:  [POST]
    
    
    
rgm_e_libreria_suministro_albaran_ajax_get_datos_libro:
    pattern: /ajax/peticion/datos/libro
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:peticionDatosLibro' }
    methods:  [POST]
    
rgm_e_libreria_suministro_albaran_ajax_get_datos_articulo:
    pattern: /ajax/peticion/datos/articulo
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:peticionDatosArticulo' }
    methods:  [POST]
    
rgm_e_libreria_suministro_albaran_ajax_get_datos_existencia:
    pattern: /ajax/peticion/datos/existencia
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:peticionDatosExistencia' }
    methods:  [POST]
    
    
    
    
rgm_e_libreria_suministro_albaran_ajax_registro_libro:
    pattern: /ajax/registro/libro
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:registroLibro' }
    methods:  [POST]

rgm_e_libreria_suministro_albaran_ajax_registro_articulo:
    pattern: /ajax/registro/articulo
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:registroArticulo' }
    methods:  [POST]

rgm_e_libreria_suministro_albaran_ajax_registro_existencia:
    pattern: /ajax/registro/existencia
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:registroExistencia' }
    methods:  [POST]
    
    
    
    
rgm_e_libreria_suministro_albaran_ajax_borrar_existencia:
    pattern: /ajax/borrar/existencia
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:borrarExistencia' }
    methods:  [POST]
    
    
    
rgm_e_libreria_suministro_albaran_ajax_plantilla_libro:
    pattern: /ajax/plantilla/libro
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:plantillaLibro' }
    
rgm_e_libreria_suministro_albaran_ajax_plantilla_articulo:
    pattern: /ajax/plantilla/articulo
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:plantillaArticulo' }
    
rgm_e_libreria_suministro_albaran_ajax_plantilla_existencia:
    pattern: /ajax/plantilla/existencia
    defaults: { _controller: 'RGMELibreriaSuministroBundle:AlbaranAjax:plantillaExistencia' }
    
    
    
    
rgm_e_libreria_suministro_articulo_crear:
    pattern:  /articulo/nuevo
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Articulo:crearArticulo' }
    
rgm_e_libreria_suministro_articulo_editar:
    pattern:  /articulo/{id}/editar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Articulo:editarArticulo' }
    
rgm_e_libreria_suministro_articulo_borrar:
    pattern:  /articulo/{id}/borrar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Articulo:borrarArticulo' }
    
rgm_e_libreria_suministro_articulo_homepage:
    pattern:  /articulo
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Articulo:verArticulos' }

rgm_e_libreria_suministro_articulo_buscar_referencia_ajax:
    pattern: /articulo/buscarAjax
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Articulo:buscarArticuloAjax' }
    methods:  [POST]

    

rgm_e_libreria_suministro_contratosuministro_crear:
    pattern:  /contratosuministro/nuevo
    defaults: { _controller: 'RGMELibreriaSuministroBundle:ContratoSuministro:crearContratoSuministro' }
    
rgm_e_libreria_suministro_contratosuministro_editar:
    pattern:  /contratosuministro/{id}/editar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:ContratoSuministro:editarContratoSuministro' }
    
rgm_e_libreria_suministro_contratosuministro_borrar:
    pattern:  /contratosuministro/{id}/borrar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:ContratoSuministro:borrarContratoSuministro' }
    
rgm_e_libreria_suministro_contratosuministro_homepage:
    pattern:  /contratosuministro
    defaults: { _controller: 'RGMELibreriaSuministroBundle:ContratoSuministro:verContratosSuministro' }
    
    
    

rgm_e_libreria_suministro_recargo_crear:
    pattern:  /recargo/nueva
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Recargo:crearRecargo' }
    
rgm_e_libreria_suministro_recargo_editar:
    pattern:  /recargo/{id}/editar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Recargo:editarRecargo' }
    
rgm_e_libreria_suministro_recargo_borrar:
    pattern:  /recargo/{id}/borrar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Recargo:borrarRecargo' }
    
rgm_e_libreria_suministro_recargo_homepage:
    pattern:  /recargo
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Recargo:verRecargos' }    
    
    

rgm_e_libreria_suministro_distribuidoras_crear:
    pattern:  /distribuidoras/nueva
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Distribuidora:crearDistribuidora' }
    
rgm_e_libreria_suministro_distribuidoras_editar:
    pattern:  /distribuidoras/{id}/editar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Distribuidora:editarDistribuidora' }
    
rgm_e_libreria_suministro_distribuidoras_borrar:
    pattern:  /distribuidoras/{id}/borrar
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Distribuidora:borrarDistribuidora' }
    
rgm_e_libreria_suministro_distribuidoras_homepage:
    pattern:  /distribuidoras
    defaults: { _controller: 'RGMELibreriaSuministroBundle:Distribuidora:verDistribuidoras' }