parameters:
#    rgarcia_entrelineas_index.example.class: RGM\eLibreria\IndexBundle\Example

services:
#    rgarcia_entrelineas_index.example:
#        class: %rgarcia_entrelineas_index.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
