rgarcia_entrelineas_localizacion_crear:
    pattern:  /localizacion/crear
    defaults: { _controller: "RGMELibreriaLibroBundle:Localizacion:crearLocalizacion" }
    
rgarcia_entrelineas_localizacion_editar:
    pattern:  /localizacion/editar/{id}
    defaults: { _controller: "RGMELibreriaLibroBundle:Localizacion:editarLocalizacion" }
    
rgarcia_entrelineas_localizacion_borrar:
    pattern:  /localizacion/borrar/{id}
    defaults: { _controller: "RGMELibreriaLibroBundle:Localizacion:borrarLocalizacion" }
    
rgarcia_entrelineas_localizacion_homepage:
    pattern:  /localizacion
    defaults: { _controller: "RGMELibreriaLibroBundle:Localizacion:verLocalizacion" }
    
    
    
    
rgarcia_entrelineas_estilo_crear:
    pattern:  /estilo/crear
    defaults: { _controller: "RGMELibreriaLibroBundle:Estilo:crearEstilo" }
    
rgarcia_entrelineas_estilo_editar:
    pattern:  /estilo/editar/{id}
    defaults: { _controller: "RGMELibreriaLibroBundle:Estilo:editarEstilo" }
    
rgarcia_entrelineas_estilo_borrar:
    pattern:  /estilo/borrar/{id}
    defaults: { _controller: "RGMELibreriaLibroBundle:Estilo:borrarEstilo" }
    
rgarcia_entrelineas_estilo_homepage:
    pattern:  /estilo
    defaults: { _controller: "RGMELibreriaLibroBundle:Estilo:verEstilo" }




rgarcia_entrelineas_editorial_buscarAjax:
    pattern:  /editorial/buscar
    defaults: { _controller: "RGMELibreriaLibroBundle:Editorial:buscar_Editorial_Ajax" }
    
rgarcia_entrelineas_editorial_crear:
    pattern:  /editorial/crear
    defaults: { _controller: "RGMELibreriaLibroBundle:Editorial:crearEditorial" }
    
rgarcia_entrelineas_editorial_editar:
    pattern:  /editorial/editar/{id}
    defaults: { _controller: "RGMELibreriaLibroBundle:Editorial:editarEditorial" }
    
rgarcia_entrelineas_editorial_borrar:
    pattern:  /editorial/borrar/{id}
    defaults: { _controller: "RGMELibreriaLibroBundle:Editorial:borrarEditorial" }
    
rgarcia_entrelineas_editorial_homepage:
    pattern:  /editorial
    defaults: { _controller: "RGMELibreriaLibroBundle:Editorial:verEditorial" }



rgarcia_entrelineas_autor_crear:
    pattern:  /autor/crear
    defaults: { _controller: "RGMELibreriaLibroBundle:Autor:crearAutor" }
    
rgarcia_entrelineas_autor_editar:
    pattern:  /autor/editar/{id}
    defaults: { _controller: "RGMELibreriaLibroBundle:Autor:editarAutor" }
    
rgarcia_entrelineas_autor_borrar:
    pattern:  /autor/borrar/{id}
    defaults: { _controller: "RGMELibreriaLibroBundle:Autor:borrarAutor" }
    
rgarcia_entrelineas_autor_homepage:
    pattern:  /autor
    defaults: { _controller: "RGMELibreriaLibroBundle:Autor:verAutor" }
    
    
    

rgm_e_libreria_librobundle_libro_buscar_referencia_ajax:
    pattern: /libro/buscarAjax
    defaults: { _controller: 'RGMELibreriaLibroBundle:Libro:buscarLibroAjax' }

rgarcia_entrelineas_libro_crear:
    pattern:  /gestor/crear/{crearMasivo}
    defaults: 
        _controller: "RGMELibreriaLibroBundle:Libro:crearLibro"
        crearMasivo: 0
    
rgarcia_entrelineas_libro_editar:
    pattern:  /gestor/editar/{isbn}
    defaults: { _controller: "RGMELibreriaLibroBundle:Libro:editarLibro" }
    
rgarcia_entrelineas_libro_borrar:
    pattern:  /gestor/borrar/{isbn}
    defaults: { _controller: "RGMELibreriaLibroBundle:Libro:borrarLibro" }
    
rgarcia_entrelineas_libro_homepage:
    pattern:  /gestor
    defaults: { _controller: "RGMELibreriaLibroBundle:Libro:verLibros" }