rgarcia_entrelineas_autor_crear:
    pattern:  /autor/crear
    defaults: { _controller: "RGMELibreriaLibroBundle:Autor:crearAutor" }
    
rgarcia_entrelineas_autor_editar:
    pattern:  /autor/editar/{id}
    defaults: { _controller: "RGMELibreriaLibroBundle:Autor:editarAutor" }
    
rgarcia_entrelineas_autor_borrar:
    pattern:  /autor/borrar/{id}
    defaults: { _controller: "RGMELibreriaLibroBundle:Autor:borrarAutor" }
    
rgarcia_entrelineas_autor_homepage:
    pattern:  /autor
    defaults: { _controller: "RGMELibreriaLibroBundle:Autor:verAutor" }
    
    
    

rgarcia_entrelineas_libro_crear:
    pattern:  /gestor/crear/{crearMasivo}
    defaults: 
        _controller: "RGMELibreriaLibroBundle:Libro:crearLibro"
        crearMasivo: 0
    
rgarcia_entrelineas_libro_editar:
    pattern:  /gestor/editar/{isbn}
    defaults: { _controller: "RGMELibreriaLibroBundle:Libro:editarLibro" }
    
rgarcia_entrelineas_libro_borrar:
    pattern:  /gestor/borrar/{isbn}
    defaults: { _controller: "RGMELibreriaLibroBundle:Libro:borrarLibro" }
    
rgarcia_entrelineas_libro_homepage:
    pattern:  /gestor
    defaults: { _controller: "RGMELibreriaLibroBundle:Libro:verLibros" }