parameters:
#    rgarcia_entrelineas_libro.example.class: RGM\eLibreria\LibroBundle\Example

services:
#    rgarcia_entrelineas_libro.example:
#        class: %rgarcia_entrelineas_libro.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
